version: "3.9"
services:
  backup:
    image: "backuper"
    container_name: "push2nextcloud"
    volumes:
      - ../data:/data:ro
    env_file:
      - .env
    #environment:
    #  - SOURCE_FILE=/data/dumb.data
    #  - DEST_FILE=dumb.data

    #  - NEXTCLOUD_USR=jack
    #  - NEXTCLOUD_PWD=secret
    #- NEXTCLOUD_URL=https://nextcloud.yourcompany.com/public.php/webdav/