version: "3.9"
services:
  backup:
    image: "satoshiengineering/push2nextcloud:latest"
    container_name: "push2nextcloud"
    volumes:
      - ../data:/backup:ro
    environment:
      - SOURCE_FILE=/data/dump.data
      - DEST_FILE=dump.data

      - NEXTCLOUD_USR=jack
      - NEXTCLOUD_PWD=secret
      - NEXTCLOUD_URL=https://nextcloud.yourcompany.com/public.php/webdav/
    # Optional run with .env file
    # env_file:
    #   - .env
